training:
  batch_size: 64
  seq_length: 16
  train_steps: 1000
  save_interval: 100

model:
  obs_dim: 29
  action_dim: 2
  stoch_dim: 32
  deter_dim: 256
  hidden_dim: 512
  discount: 0.99
  horizon: 15

env:
  grid_size: 20
  max_steps: 100
  static_obstacles: 5
  dynamic_obstacles: 2

testing:
  test_episodes: 20           # 测试回合数
  render_interval: 3          # 渲染间隔（每N回合渲染一次）
  save_trajectory: true        # 是否保存轨迹图
  model_path: "dreamer_900.pth"  # 训练模型路径